### ISSUE TITLE
Switch order of octave and dot recognition

### ISSUE THREAD

**Issue by mcauser** [adamonsoon/rtttl-play#1]
I discovered your RTTTL player via Google. Nice!
https://adamonsoon.github.io/rtttl-play/

Noticed it played The Entertainer incorrectly. Specifically the `2c.6` note.
```
Entertainer:d=4,o=5,b=140:8d,8d#,8e,c6,8e,c6,8e,2c.6,8c6,8d6,8d#6,8e6,8c6,8d6,e6,8b,d6,2c6,p,8d,8d#,8e,c6,8e,c6,8e,2c.6,8p,8a,8g,8f#,8a,8c6,e6,8d6,8c6,8a,2d6
```

Noticed you already fixed the problem here:
https://github.com/adamonsoon/rtttl-parse/commit/542240255693264f7c5076cd7851b1f4100224d8

Seems you just need to update `rtttl-parse` to `1.3.1` in package.json and rebuild.

**Comment by adamonsoon** [comment]
Hey @mcauser, thanks for letting me know!
It should work as expected now :sweat_smile:
